### ISSUE TITLE
Don’t t know how to install

### ISSUE THREAD

**Issue by ThrGrrd** [ProtoPie/android-arduino-bridge-sample#2]
Hi,

Maybe I'm totally getting this wrong but how do I install this bridge app on my android phone?

Thanks in advance

**Comment by john-song** [comment]
Hi ThrGrrd,

This is source code of a sample bridge app and it's for those who know how to write Android code.

Therefore you need to know how to build an Android app from source code in order to install it on your Android phone.

But if you are going to use it without modification, you can use the following instructions:

1. Download and install Android Studio
2. Download and unzip the source code
3. Run Android Studio and click "Open an existing Android Studio project"
4. Select the unzipped source code directory
5. Build > Build Bundle(s) / APK(s) > Build APK(s)

If everything goes well, Android Studio will let you know where the APK file is generated.

**Comment by ThrGrrd** [comment]
Hi John-song,

Is there any way you can make the APK for me, because I tried to follow the steps you said but it just doesn't work...

I want to connect my Arduino to my Android to use Protopie.
Like in this article: https://blog.protopie.io/arduino-prototyping-with-protopie-7932ececfec5
It mentions a link to this github project.

I don't know anything about making apps, I just want to use this feature.

Greetings
Thor
